name: Release Check
on:
  # Run on mainline branches
  push:
    branches:
      - 'master'
      - 'release-*'
  # Run on branch/tag creation
  create:
  # Run on Pull Requests
  pull_request:

jobs:
  goreleaser-check:
    name: goreleaser-check
    runs-on: ubuntu-22.04
    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        fetch-depth: 0
    - name: Set up Go 1.21
      uses: actions/setup-go@v4
      with:
        go-version: 1.21.x
    - name: Run GoReleaser Check
      uses: goreleaser/goreleaser-action@v4
      with:
        distribution: goreleaser
        version: v2
        args: check

